steps:

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      docker build -t asia-south1-docker.pkg.dev/$PROJECT_ID/proploy-frontend/proploy-frontend . \
        --build-arg NEXT_PUBLIC_SUPABASE_URL=$_NEXT_PUBLIC_SUPABASE_URL \
        --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=$_NEXT_PUBLIC_SUPABASE_ANON_KEY \
        --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY \
        --build-arg NEXT_PUBLIC_APP_URL=$_NEXT_PUBLIC_APP_URL

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/proploy-frontend/proploy-frontend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'proploy-frontend'
    - '--image'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/proploy-frontend/proploy-frontend'
    - '--region'
    - 'asia-south1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--service-account'
    - 'proploy-deployer@coral-polymer-484212-r3.iam.gserviceaccount.com'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/proploy-frontend/proploy-frontend'

substitutions:
  _NEXT_PUBLIC_SUPABASE_URL: "https://wyoaqtliilrzomfuityd.supabase.co"
  _NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5b2FxdGxpaWxyem9tZnVpdHlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NzAzMzYsImV4cCI6MjA3NjA0NjMzNn0.Kw2tPr2dP2Ei-oW4AfX3MKe9CpnHNOXyYOqV0AJxMNM"
  _NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_test_c2hhcmluZy1oaXBwby03My5jbGVyay5hY2NvdW50cy5kZXYk"
  _NEXT_PUBLIC_APP_URL: "https://proploy.io"

options:
  logging: CLOUD_LOGGING_ONLY
