/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type SocialProof = {
  count?: string;
  label?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Photo = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type LegalPage = {
  _id: string;
  _type: "legalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  effectiveDate?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  publishedAt?: string;
  author?: AuthorReference;
  category?: CategoryReference;
  tags?: Array<string>;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  social?: {
    linkedin?: string;
    x?: string;
    website?: string;
  };
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: Array<
    | ({
        _key: string;
      } & HomeHeroSection)
    | ({
        _key: string;
      } & MarketingHeroSection)
    | ({
        _key: string;
      } & ValuePropsSection)
    | ({
        _key: string;
      } & IndustriesSection)
    | ({
        _key: string;
      } & HowItWorksSection)
    | ({
        _key: string;
      } & IntegrationsSection)
    | ({
        _key: string;
      } & ClosingCtaSection)
    | ({
        _key: string;
      } & MetricsSection)
    | ({
        _key: string;
      } & ComparisonSection)
    | ({
        _key: string;
      } & SolutionCardsSection)
    | ({
        _key: string;
      } & CaseStudiesSection)
    | ({
        _key: string;
      } & TeamSection)
    | ({
        _key: string;
      } & ValuesSection)
    | ({
        _key: string;
      } & FaqSection)
    | ({
        _key: string;
      } & MapSection)
    | ({
        _key: string;
      } & QuoteTestimonialSection)
    | ({
        _key: string;
      } & ProseBlock)
    | ({
        _key: string;
      } & LogoGridSection)
    | ({
        _key: string;
      } & LogoMarqueeSection)
  >;
  seo?: Seo;
};

export type FooterSettings = {
  _id: string;
  _type: "footerSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  columns?: Array<{
    title?: string;
    links?: Array<{
      label?: string;
      href?: string;
      _key: string;
    }>;
    _key: string;
  }>;
  bottomStrip?: {
    copyright?: string;
    legalLinks?: Array<{
      label?: string;
      href?: string;
      _key: string;
    }>;
  };
  smallPrint?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  aboutLinks?: Array<{
    label?: string;
    href?: string;
    description?: string;
    _key: string;
  }>;
  ctaLabels?: {
    signIn?: string;
    getStarted?: string;
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandName?: string;
  legalName?: string;
  tagline?: string;
  contactEmail?: string;
  social?: Array<{
    platform?:
      | "x"
      | "linkedin"
      | "instagram"
      | "youtube"
      | "tiktok"
      | "dribbble"
      | "github";
    href?: string;
    _key: string;
  }>;
};

export type LogoMarqueeSection = {
  _type: "logoMarqueeSection";
  logos?: Array<string>;
  direction?: "left" | "right";
};

export type LogoGridSection = {
  _type: "logoGridSection";
  eyebrow?: string;
  title?: string;
  logos?: Array<string>;
};

export type ProseBlock = {
  _type: "proseBlock";
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  width?: "narrow" | "default" | "wide";
};

export type QuoteTestimonialSection = {
  _type: "quoteTestimonialSection";
  quote?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  attribution?: string;
  role?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type MapSection = {
  _type: "mapSection";
  eyebrow?: string;
  title?: string;
  subtitle?: string;
  pins?: Array<{
    top?: string;
    left?: string;
    region?: string;
    _key: string;
  }>;
};

export type FaqSection = {
  _type: "faqSection";
  eyebrow?: string;
  title?: string;
  faqs?: Array<{
    q?: string;
    a?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _key: string;
  }>;
};

export type ValuesSection = {
  _type: "valuesSection";
  eyebrow?: string;
  title?: string;
  values?: Array<{
    iconKey?:
      | "AlertTriangle"
      | "ArrowLeft"
      | "ArrowRight"
      | "ArrowUpRight"
      | "BarChart3"
      | "Building2"
      | "Camera"
      | "Check"
      | "CheckCircle2"
      | "Clock3"
      | "ClipboardCheck"
      | "Command"
      | "CreditCard"
      | "Download"
      | "Eye"
      | "FileCheck2"
      | "FileSignature"
      | "FileText"
      | "Gauge"
      | "GitCompareArrows"
      | "Globe"
      | "Heart"
      | "Home"
      | "Inbox"
      | "Loader2"
      | "LockKeyhole"
      | "Mail"
      | "MapPin"
      | "MessageCircle"
      | "MessageSquareMore"
      | "Package2"
      | "PenLine"
      | "Plug"
      | "Plus"
      | "Receipt"
      | "RefreshCw"
      | "RotateCcw"
      | "Save"
      | "Scale"
      | "ScrollText"
      | "Send"
      | "ShieldCheck"
      | "Sparkles"
      | "Star"
      | "Trash2"
      | "TrendingUp"
      | "UserRound"
      | "Wallet"
      | "X"
      | "XCircle"
      | "Zap";
    title?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _key: string;
  }>;
};

export type TeamSection = {
  _type: "teamSection";
  eyebrow?: string;
  title?: string;
  members?: Array<{
    name?: string;
    role?: string;
    bio?: string;
    color?: string;
    photo?: Photo;
    _key: string;
  }>;
};

export type CaseStudiesSection = {
  _type: "caseStudiesSection";
  eyebrow?: string;
  title?: string;
  cases?: Array<{
    company?: string;
    color?: string;
    quote?: string;
    _key: string;
  }>;
};

export type SolutionCardsSection = {
  _type: "solutionCardsSection";
  eyebrow?: string;
  title?: string;
  cards?: Array<{
    iconKey?:
      | "AlertTriangle"
      | "ArrowLeft"
      | "ArrowRight"
      | "ArrowUpRight"
      | "BarChart3"
      | "Building2"
      | "Camera"
      | "Check"
      | "CheckCircle2"
      | "Clock3"
      | "ClipboardCheck"
      | "Command"
      | "CreditCard"
      | "Download"
      | "Eye"
      | "FileCheck2"
      | "FileSignature"
      | "FileText"
      | "Gauge"
      | "GitCompareArrows"
      | "Globe"
      | "Heart"
      | "Home"
      | "Inbox"
      | "Loader2"
      | "LockKeyhole"
      | "Mail"
      | "MapPin"
      | "MessageCircle"
      | "MessageSquareMore"
      | "Package2"
      | "PenLine"
      | "Plug"
      | "Plus"
      | "Receipt"
      | "RefreshCw"
      | "RotateCcw"
      | "Save"
      | "Scale"
      | "ScrollText"
      | "Send"
      | "ShieldCheck"
      | "Sparkles"
      | "Star"
      | "Trash2"
      | "TrendingUp"
      | "UserRound"
      | "Wallet"
      | "X"
      | "XCircle"
      | "Zap";
    iconColor?: "white" | "gray";
    title?: string;
    body?: string;
    _key: string;
  }>;
};

export type ComparisonSection = {
  _type: "comparisonSection";
  eyebrow?: string;
  title?: string;
  columns?: Array<string>;
  sections?: Array<{
    title?: string;
    rows?: Array<{
      label?: string;
      values?: Array<
        {
          _key: string;
        } & ComparisonCell
      >;
      _key: string;
    }>;
    _key: string;
  }>;
};

export type MetricsSection = {
  _type: "metricsSection";
  variant?: "simple" | "detailed";
  items?: Array<{
    value?: string;
    label?: string;
    title?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _key: string;
  }>;
};

export type ClosingCtaSection = {
  _type: "closingCtaSection";
  eyebrow?: string;
  title?: string;
  subtitle?: string;
  buttonLabel?: string;
  submittedLabel?: string;
  placeholder?: string;
  helperText?: string;
  successMessage?: string;
};

export type IntegrationsSection = {
  _type: "integrationsSection";
  eyebrow?: string;
  title?: string;
  ringA?: Array<string>;
  ringB?: Array<string>;
};

export type HowItWorksSection = {
  _type: "howItWorksSection";
  eyebrow?: string;
  title?: string;
  steps?: Array<{
    n?: string;
    key?: string;
    title?: string;
    lead?: string;
    body?: string;
    bullets?: Array<string>;
    _key: string;
  }>;
};

export type IndustriesSection = {
  _type: "industriesSection";
  eyebrow?: string;
  title?: string;
  industries?: Array<{
    key?: string;
    label?: string;
    solutions?: Array<{
      name?: string;
      blurb?: string;
      proof?: string;
      proofLabel?: string;
      _key: string;
    }>;
    _key: string;
  }>;
};

export type ValuePropsSection = {
  _type: "valuePropsSection";
  eyebrow?: string;
  title?: string;
  points?: Array<{
    n?: string;
    metric?: string;
    metricLabel?: string;
    title?: string;
    body?: string;
    _key: string;
  }>;
};

export type MarketingHeroSection = {
  _type: "marketingHeroSection";
  eyebrow?: string;
  title?: string;
  subtitle?: string;
  ctas?: Array<
    {
      _key: string;
    } & Cta
  >;
};

export type HomeHeroSection = {
  _type: "homeHeroSection";
  eyebrow?: string;
  rotatingWords?: Array<string>;
  subtitle?: string;
  socialProof?: SocialProof;
};

export type ComparisonCell = {
  _type: "comparisonCell";
  kind?: "check" | "text" | "dash";
  checked?: boolean;
  text?: string;
};

export type Cta = {
  _type: "cta";
  label?: string;
  href?: string;
  variant?: "primary" | "secondary";
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SocialProof
  | SanityImageAssetReference
  | Photo
  | LegalPage
  | Seo
  | Slug
  | AuthorReference
  | CategoryReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Category
  | Author
  | Page
  | FooterSettings
  | Navigation
  | SiteSettings
  | LogoMarqueeSection
  | LogoGridSection
  | ProseBlock
  | QuoteTestimonialSection
  | MapSection
  | FaqSection
  | ValuesSection
  | TeamSection
  | CaseStudiesSection
  | SolutionCardsSection
  | ComparisonSection
  | MetricsSection
  | ClosingCtaSection
  | IntegrationsSection
  | HowItWorksSection
  | IndustriesSection
  | ValuePropsSection
  | MarketingHeroSection
  | HomeHeroSection
  | ComparisonCell
  | Cta
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
