/**
 * Sanitize the HTML Sam's document tools return before it is rendered inline.
 * The HTML is generated by our own backend, but it is still model output, so
 * anything executable is dropped: scripts, embeds, forms, event handlers,
 * javascript: URLs and CSS that can load remote content. Classes and inline
 * layout styles survive so the Tailwind-classed tables keep their shape.
 */

const BLOCKED_TAGS = new Set([
  'script',
  'style',
  'iframe',
  'frame',
  'object',
  'embed',
  'link',
  'meta',
  'base',
  'form',
  'input',
  'button',
  'textarea',
  'select',
  'template',
  'noscript',
  'svg',
  'math',
])

const URL_ATTRIBUTES = new Set(['href', 'src', 'xlink:href', 'srcset', 'action', 'formaction'])

function isSafeUrl(value: string): boolean {
  const trimmed = value.trim().toLowerCase()
  if (!trimmed) return true
  if (trimmed.startsWith('javascript:') || trimmed.startsWith('vbscript:')) return false
  if (trimmed.startsWith('data:')) return trimmed.startsWith('data:image/')
  return true
}

export function sanitizeDocumentHtml(html: string): string {
  if (!html || typeof DOMParser === 'undefined') return ''
  const parsed = new DOMParser().parseFromString(`<body>${html}</body>`, 'text/html')
  const elements = Array.from(parsed.body.querySelectorAll('*'))

  for (const element of elements) {
    if (BLOCKED_TAGS.has(element.tagName.toLowerCase())) {
      element.remove()
      continue
    }
    for (const attribute of Array.from(element.attributes)) {
      const name = attribute.name.toLowerCase()
      const value = attribute.value
      if (name.startsWith('on') || name === 'srcdoc') {
        element.removeAttribute(attribute.name)
      } else if (URL_ATTRIBUTES.has(name) && !isSafeUrl(value)) {
        element.removeAttribute(attribute.name)
      } else if (name === 'style' && /url\s*\(|expression\s*\(|@import/i.test(value)) {
        element.removeAttribute(attribute.name)
      }
    }
    if (element.tagName.toLowerCase() === 'a') {
      element.setAttribute('rel', 'noopener noreferrer')
      element.setAttribute('target', '_blank')
    }
  }

  return parsed.body.innerHTML
}
